# Generated by Django 4.2.30 on 2026-08-01 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pendaftaran', '0002_alter_pendaftaran_kode_pendaftaran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_gigi', models.CharField(choices=[('PERMANEN', 'Gigi Permanen'), ('SULUNG', 'Gigi Sulung')], default='PERMANEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pendaftaran', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odontogram', to='pendaftaran.pendaftaran')),
            ],
            options={
                'db_table': 'odontogram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KondisiGigi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_gigi', models.CharField(max_length=5)),
                ('kondisi', models.CharField(choices=[('SEHAT', 'Sehat / OK'), ('KARIES', 'Karies'), ('TUMPATAN', 'Tumpatan / Tambalan'), ('HILANG', 'Hilang / Dicabut'), ('MAHKOTA', 'Mahkota / Bridge'), ('RCT', 'Perawatan Saluran Akar (RCT)'), ('INDIKASI_CABUT', 'Indikasi Cabut'), ('PROTESA', 'Protesa / Gigi Palsu')], default='SEHAT', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('odontogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kondisi', to='odontogram.odontogram')),
            ],
            options={
                'db_table': 'kondisi_gigi',
                'ordering': ['nomor_gigi'],
                'unique_together': {('odontogram', 'nomor_gigi')},
            },
        ),
    ]
