# Generated by Django 4.2.30 on 2026-08-11 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterObat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('dosis_default', models.CharField(blank=True, max_length=100, null=True)),
                ('satuan', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'master_obat',
                'ordering': ['nama'],
            },
        ),
        migrations.RemoveField(
            model_name='resepdetail',
            name='nama_obat',
        ),
        migrations.AddField(
            model_name='resepdetail',
            name='nama_obat_custom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resepdetail',
            name='obat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resep.masterobat'),
        ),
    ]
