# Generated by Django 4.2.30 on 2026-10-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0002_masterobat_remove_resepdetail_nama_obat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resepdetail',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='resepdetail',
            name='jumlah',
        ),
        migrations.RemoveField(
            model_name='resepdetail',
            name='nama_obat_custom',
        ),
    ]
