# Generated by Django 4.2.30 on 2026-10-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0003_remove_resepdetail_dosis_remove_resepdetail_jumlah_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resepdetail',
            name='frekuensi',
        ),
        migrations.AddField(
            model_name='resepdetail',
            name='jumlah',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
