# Generated by Django 4.2.30 on 2026-07-22 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pasien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_kunjungan', models.DateField()),
                ('waktu_daftar', models.DateTimeField(auto_now_add=True)),
                ('cara_daftar', models.CharField(choices=[('ONLINE', 'Online'), ('ADMISI', 'Admisi'), ('MANDIRI', 'Mandiri')], default='ONLINE', max_length=10)),
                ('kode_pendaftaran', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('TERDAFTAR', 'Terdaftar'), ('MENUNGGU', 'Menunggu'), ('DIPANGGIL', 'Dipanggil'), ('DIPERIKSA', 'Diperiksa'), ('SELESAI', 'Selesai')], default='TERDAFTAR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftaran', to='pasien.pasien')),
            ],
            options={
                'db_table': 'pendaftaran',
                'ordering': ['-waktu_daftar'],
            },
        ),
    ]
