# Generated by Django 4.2.30 on 2026-07-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='kode_pendaftaran',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
