# Generated by Django 4.2.30 on 2026-08-11 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0002_alter_pendaftaran_kode_pendaftaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeadaanKhusus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hamil', models.CharField(blank=True, choices=[('TR1', 'Trimester 1'), ('TR2', 'Trimester 2'), ('TR3', 'Trimester 3')], max_length=3, null=True)),
                ('hipertensi', models.BooleanField(default=False)),
                ('hipertensi_keterangan', models.TextField(blank=True, null=True)),
                ('riwayat_jantung', models.BooleanField(default=False)),
                ('riwayat_jantung_nama_dokter', models.CharField(blank=True, max_length=200, null=True)),
                ('alergi_obat', models.BooleanField(default=False)),
                ('alergi_obat_nama', models.CharField(blank=True, max_length=200, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pendaftaran', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keadaan_khusus', to='pendaftaran.pendaftaran')),
            ],
            options={
                'db_table': 'keadaan_khusus',
            },
        ),
    ]
