# Generated by Django 4.2.30 on 2026-07-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=200)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_hp', models.CharField(max_length=20)),
                ('no_ktp', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pasien',
                'ordering': ['-created_at'],
            },
        ),
    ]
