# Generated by Django 4.2.30 on 2026-07-22 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pendaftaran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antrian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('nomor_antrian', models.CharField(max_length=10)),
                ('waktu_checkin', models.DateTimeField()),
                ('waktu_dipanggil', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu'), ('DIPANGGIL', 'Dipanggil'), ('DIPERIKSA', 'Diperiksa'), ('SELESAI', 'Selesai')], default='MENUNGGU', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pendaftaran', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antrian', to='pendaftaran.pendaftaran')),
            ],
            options={
                'db_table': 'antrian',
                'ordering': ['tanggal', 'nomor_antrian'],
                'unique_together': {('tanggal', 'nomor_antrian')},
            },
        ),
    ]
